AWSTemplateFormatVersion: "2010-09-09"
Description: Test suite for EKS Quick Start. (qs-1r0qgtna3)
Metadata:
  QSLint:
    Exclusions: [W9002, W9003, W9004, W9006]
Parameters:
  ClusterName:
    Type: String
Resources:
  TestKubeGet:
    Type: "AWSQS::Kubernetes::Get"
    Properties:
      ClusterName: !Ref ClusterName
      Namespace: kube-system
      Name: cm/aws-auth
      JsonPath: '{.data.mapRoles}'
  TestKubeApply:
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: !Ref ClusterName
      Namespace: kube-system
      Manifest: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: cfn-apply-test
        data:
          this: was-made-by-cfn
Outputs:
  TestKubeApplyResponse:
    Value: !GetAtt TestKubeApply.Uid
  TestKubeApplyId:
    Value: !GetAtt TestKubeApply.ResourceVersion
  TestKubeGetResponse:
    Value: !GetAtt TestKubeGet.Response
  TestKubeGetId:
    Value: !GetAtt TestKubeGet.Id
