AWSTemplateFormatVersion: "2010-09-09"
Description: Test suite for EKS Quick Start. (qs-1r0qgtna3)
Metadata:
  QSLint:
    Exclusions: [W9002, W9003, W9004, W9006]
Parameters:
  ClusterName:
    Type: String
  TestWindows:
    Type: String
Conditions:
  EnableWindows: !Equals [!Ref TestWindows, 'Enabled']
Resources:
  TestKubeGet:
    Type: "AWSQS::Kubernetes::Get"
    Properties:
      ClusterName: !Ref ClusterName
      Namespace: kube-system
      Name: cm/aws-auth
      JsonPath: '{.data.mapRoles}'
  TestKubeApply:
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: !Ref ClusterName
      Namespace: kube-system
      Manifest: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: test-job
        spec:
          template:
            spec:
              containers:
              - name: test-job
                image: amazonlinux:2
                command: ["date"]
              restartPolicy: OnFailure
          backoffLimit: 4
  EnableWindows:
    Type: "AWSQS::Kubernetes::Resource"
    Condition: EnableWindows
    Properties:
      ClusterName: !Ref ClusterName
      Namespace: kube-system
      Manifest: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: windows-test
        spec:
          template:
            spec:
              nodeSelector:
                beta.kubernetes.io/os: windows
              containers:
              - name: windows-test-container
                image: microsoft/windowsservercore
                command: ["hostname"]
              restartPolicy: OnFailure
          backoffLimit: 4
Outputs:
  TestKubeApplyResponse:
    Value: !GetAtt TestKubeApply.Uid
  TestKubeApplyId:
    Value: !GetAtt TestKubeApply.ResourceVersion
  TestKubeGetResponse:
    Value: !GetAtt TestKubeGet.Response
  TestKubeGetId:
    Value: !GetAtt TestKubeGet.Id
