AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys Lambda functions required for the AWS EKS Quick Start (qs-1p7nknoh4)
Metadata:
  QSLint:
    Exclusions: [W9002, W9003, W9004, W9006]
Parameters:
  LambdaZipsBucketName:
    Description: Bucket Name where the lambda zip files should be placed
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/.]*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), dots(.) and forward slash (/).
    Default: quickstart-amazon-eks/
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), dots(.) and
      forward slash (/).
    Type: String
  KubernetesAdminRoleArn:
    Type: String
  VPCID:
    Type: AWS::EC2::VPC::Id
  ControlPlaneSecurityGroup:
    Type: String
  EKSSubnetIds:
    Type: List<String>
  EKSClusterName:
    Type: String
Mappings:
  Config:
    Prefix: { Value: 'eks-quickstart' }
Resources:
  LambdaSGCleanup:
    Type: Custom::LambdaSGCleanup
    Properties:
      ServiceToken: !Sub ['arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:${Prefix}-CleanupSecurityGroupDependencies', {Prefix: !FindInMap [Config, Prefix, Value]}]
      Region: !Ref "AWS::Region"
      SecurityGroups:
        - !Ref EKSLambdaSecurityGroup
  EKSLambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for lambda to communicate with cluster API
      VpcId: !Ref VPCID
  ClusterControlPlaneSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Allow lambda to communicate with the cluster API Server
      GroupId: !Ref ControlPlaneSecurityGroup
      SourceSecurityGroupId: !Ref EKSLambdaSecurityGroup
      IpProtocol: tcp
      ToPort: 443
      FromPort: 443
  GetKubectlLayerArn:
    Type: Custom::CliQuery
    Properties:
      ServiceToken: !Sub ['arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:${Prefix}-ResourceReader', {Prefix: !FindInMap [Config, Prefix, Value]}]
      AwsCliCommand: !Sub
      - |
        lambda list-layer-versions --layer-name ${Prefix}-Kubectl --query 'max_by(LayerVersions, &Version)'
      - Prefix: !FindInMap [Config, Prefix, Value]
      IdField: 'LayerVersionArn'
  GetCrhelperLayerArn:
    Type: Custom::CliQuery
    Properties:
      ServiceToken: !Sub ['arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:${Prefix}-ResourceReader', {Prefix: !FindInMap [Config, Prefix, Value]}]
      AwsCliCommand: !Sub
      - |
        lambda list-layer-versions --layer-name ${Prefix}-Crhelper --query 'max_by(LayerVersions, &Version)'
      - Prefix: !FindInMap [Config, Prefix, Value]
      IdField: 'LayerVersionArn'
  GetAwsCliLayerArn:
    Type: Custom::CliQuery
    Properties:
      ServiceToken: !Sub ['arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:${Prefix}-ResourceReader', {Prefix: !FindInMap [Config, Prefix, Value]}]
      AwsCliCommand: !Sub
      - |
        lambda list-layer-versions --layer-name ${Prefix}-AwsCli --query 'max_by(LayerVersions, &Version)'
      - Prefix: !FindInMap [Config, Prefix, Value]
      IdField: 'LayerVersionArn'
  KubeManifestLambda:
    DependsOn: LambdaSGCleanup
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "EKS-QuickStart-KubeManifest-${EKSClusterName}"
      Handler: lambda_function.lambda_handler
      MemorySize: 256
      Role: !Ref KubernetesAdminRoleArn
      Runtime: python3.7
      Timeout: 900
      Layers: [!Ref GetAwsCliLayerArn, !Ref GetCrhelperLayerArn, !Ref GetKubectlLayerArn]
      Code:
        S3Bucket: !Ref LambdaZipsBucketName
        S3Key: !Sub '${QSS3KeyPrefix}functions/packages/KubeManifest/lambda.zip'
      Environment: { Variables: { KUBECONFIG: /tmp/.kube/config } }
      VpcConfig:
        SecurityGroupIds: [!Ref EKSLambdaSecurityGroup]
        SubnetIds: !Ref EKSSubnetIds
  KubeGetLambda:
    DependsOn: LambdaSGCleanup
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "EKS-QuickStart-KubeGet-${EKSClusterName}"
      Handler: lambda_function.lambda_handler
      MemorySize: 256
      Role: !Ref KubernetesAdminRoleArn
      Runtime: python3.7
      Timeout: 900
      Layers: [!Ref GetAwsCliLayerArn, !Ref GetCrhelperLayerArn, !Ref GetKubectlLayerArn]
      Code:
        S3Bucket: !Ref LambdaZipsBucketName
        S3Key: !Sub '${QSS3KeyPrefix}functions/packages/KubeGet/lambda.zip'
      Environment: { Variables: { KUBECONFIG: /tmp/.kube/config } }
      VpcConfig:
        SecurityGroupIds: [!Ref EKSLambdaSecurityGroup]
        SubnetIds: !Ref EKSSubnetIds
